package com.filesigner.util

import android.content.ContentResolver
import android.content.ContentValues
import android.content.Context
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.properties.TextAlignment
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class DebugPdfGenerator @Inject constructor(
    @ApplicationContext private val context: Context
) : SamplePdfGenerator {

    private val contentResolver: ContentResolver = context.contentResolver

    override fun isAvailable(): Boolean = true

    override fun generateSamplePdf(title: String, content: String): Result<Uri> {
        return try {
            val actualContent = content.ifEmpty { generateDefaultContent() }
            val actualTitle = title.ifEmpty { "Sample Document" }
            val fileName = "sample_${System.currentTimeMillis()}.pdf"

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                generatePdfScoped(fileName, actualTitle, actualContent)
            } else {
                generatePdfLegacy(fileName, actualTitle, actualContent)
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun generatePdfScoped(
        fileName: String,
        title: String,
        content: String
    ): Result<Uri> {
        val contentValues = ContentValues().apply {
            put(MediaStore.Downloads.DISPLAY_NAME, fileName)
            put(MediaStore.Downloads.MIME_TYPE, "application/pdf")
            put(MediaStore.Downloads.IS_PENDING, 1)
        }

        val uri = contentResolver.insert(
            MediaStore.Downloads.EXTERNAL_CONTENT_URI,
            contentValues
        ) ?: return Result.failure(Exception("Could not create PDF file"))

        return try {
            contentResolver.openOutputStream(uri)?.use { outputStream ->
                createPdfDocument(outputStream, title, content)
            }

            contentValues.clear()
            contentValues.put(MediaStore.Downloads.IS_PENDING, 0)
            contentResolver.update(uri, contentValues, null, null)

            Result.success(uri)
        } catch (e: Exception) {
            contentResolver.delete(uri, null, null)
            Result.failure(e)
        }
    }

    @Suppress("DEPRECATION")
    private fun generatePdfLegacy(
        fileName: String,
        title: String,
        content: String
    ): Result<Uri> {
        val downloadsDir = Environment.getExternalStoragePublicDirectory(
            Environment.DIRECTORY_DOWNLOADS
        )
        val pdfFile = File(downloadsDir, fileName)

        return try {
            FileOutputStream(pdfFile).use { outputStream ->
                createPdfDocument(outputStream, title, content)
            }
            Result.success(Uri.fromFile(pdfFile))
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun createPdfDocument(
        outputStream: java.io.OutputStream,
        title: String,
        content: String
    ) {
        val pdfWriter = PdfWriter(outputStream)
        val pdfDocument = PdfDocument(pdfWriter)
        val document = Document(pdfDocument)

        document.add(
            Paragraph(title)
                .setFontSize(24f)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20f)
        )

        val dateFormat = SimpleDateFormat("MMMM dd, yyyy 'at' HH:mm:ss", Locale.US)
        document.add(
            Paragraph("Generated on: ${dateFormat.format(Date())}")
                .setFontSize(10f)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(30f)
        )

        content.split("\n\n").forEach { paragraph ->
            document.add(
                Paragraph(paragraph)
                    .setFontSize(12f)
                    .setTextAlignment(TextAlignment.JUSTIFIED)
                    .setMarginBottom(12f)
            )
        }

        document.add(
            Paragraph("This document was generated by File Signer app for testing digital signatures.")
                .setFontSize(8f)
                .setItalic()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(40f)
        )

        document.close()
    }

    private fun generateDefaultContent(): String {
        return """
            This is a sample PDF document created for testing the digital signature functionality of the File Signer application. The document contains multiple paragraphs of text to simulate a real-world document that might need to be digitally signed.

            Digital signatures provide a way to verify the authenticity and integrity of electronic documents. When you sign this document using the File Signer app, a cryptographic signature is generated using the ECDSA (Elliptic Curve Digital Signature Algorithm) with the P-256 curve.

            The signature is computed over the entire contents of the file, ensuring that any modification to the document after signing can be detected. This provides non-repudiation, meaning the signer cannot deny having signed the document.

            The private key used for signing is securely stored in the Android Keystore, which provides hardware-backed security on supported devices. The key never leaves the secure hardware, making it extremely difficult for malicious applications to access or extract it.

            This sample document can be used to test the signing functionality. After signing, the signature will be saved as a separate .sig file alongside the original PDF. You can then use the public key to verify that the signature is valid and that the document has not been tampered with.

            Thank you for using File Signer. This application demonstrates the implementation of Clean Architecture and MVVM patterns in Android development, combined with secure cryptographic operations.
        """.trimIndent()
    }
}
